### ISSUE TITLE
Safe Mode problem

### ISSUE THREAD

**Issue by aegypius** [aegypius/wp-da-widgets#1]
From Honigkuchenwolf

>  Hi,
> 
> I’ve got the follwoing error message:
> 
>    Warning: curl_setopt() [function.curl-setopt]: CURLOPT_FOLLOWLOCATION cannot be activated when in safe_mode or an open_basedir is set in [...]wp-content/plugins/deviantart-widgets/libraries/Feed.php on line 26
> 
> what I have done wrong?

**Comment by aegypius** [comment]
I need to found a workaround to fix this error in safe_mode

**Comment by Honigkuchenwolf** [comment]
Oh and how can I quit the safe mode? It that a wordpress thing? or on your plugin?

**Comment by aegypius** [comment]
safe_mode is a PHP thing ! 

safe_mode or open_basedir may have been set by your hosting, albeit it's not a bad thing (it's a little safer). 

CURLOPT_FOLLOWLOCATION option is not mandatory for deviantART so I think I haved fixed issue in 0.1.3, please update plugin and tell me if it works as expected !

**Comment by Honigkuchenwolf** [comment]
hum Download doesn't start... can't upgrade from Wordpress either.

**Comment by aegypius** [comment]
It works for me on github and wordpress.org too

**Comment by Honigkuchenwolf** [comment]
ok downloaded and installed

Now it don't show any mistake anymore, but neither the feed I get him. He shows nothing.
I tried the following both feeds: http://backend.deviantart.com/rss.xml?q=gallery%3AWen-M%2F8496170&type=deviation&offset=0

http://backend.deviantart.com/rss.xml?q=gallery:wen-m

the rest of the widget was filled from me with the following informations:

Title: Wen-M
Content: Gallrey
Deviant: (the feedlink)
Items to display: 4
Content Rating: Allow Adult content

**Comment by aegypius** [comment]
Try to disable cache and thumbnails to check if other errors shows up.

I am sorry you have some much trouble with my plugin. I'll try to fix this tomorrow.

Just found another bug : 
Thumbnails are not correctly generated with galleries

**Comment by Honigkuchenwolf** [comment]
Ok I disabled my cache and tried... nothing happend.

No Prob for the issues your Plugin is in beta phase and when it is finished it could be a real cool widget. But you need testers who find the mistakes or have problems so you can solve it ;)

**Comment by aegypius** [comment]
I've just fixed gallery thumbnail generation, i have tested it on my own website with your parameters it seems to work great now.

You can try it on yours, please click on the "Download Source"  button, i've not yet release 0.1.4

**Comment by Honigkuchenwolf** [comment]
hum which version should I load? the master version?

**Comment by Honigkuchenwolf** [comment]
ok after installing the master version, he tells me a) to update to version 0.1.3 and a big failure 

Warning: gzopen(/da-widgets-0a78d3eef3f3f72e21a074337ca6c93aa00bdc4d.html.gz) [function.gzopen]: failed to open stream: Permission denied in /www/htdocs/w00aa2aa/hokuwo.de/wp-content/plugins/aegypius-wp-da-widgets-5d6ed07/libraries/Cache.php  on line 27

Warning: gzwrite(): supplied argument is not a valid stream resource in /www/htdocs/w00aa2aa/hokuwo.de/wp-content/plugins/aegypius-wp-da-widgets-5d6ed07/libraries/Cache.php on line 28

Warning: gzclose(): supplied argument is not a valid stream resource in /www/htdocs/w00aa2aa/hokuwo.de/wp-content/plugins/aegypius-wp-da-widgets-5d6ed07/libraries/Cache.php on line 29

Warning: curl_setopt() [function.curl-setopt]: CURLOPT_FOLLOWLOCATION cannot be activated when in safe_mode or an open_basedir is set in /www/htdocs/w00aa2aa/hokuwo.de/wp-content/plugins/aegypius-wp-da-widgets-5d6ed07/libraries/Feed.php on line 26

**Comment by aegypius** [comment]
Sorry for this, master is not up to date, please consider using branch 0.1x.

**Comment by Honigkuchenwolf** [comment]
hmm ok when I click on downloading 0.1x I get the 0.1.3 version... and there is no change on the widget...

**Comment by Honigkuchenwolf** [comment]
ok perhaps I'm not smart enough to find the file you want me to download ^^!

**Comment by aegypius** [comment]
Ok the current release is still 0.1.3 : you can download current maintenance release here : http://cloud.github.com/downloads/aegypius/wp-da-widgets/0.1.3-maint.zip

**Comment by Honigkuchenwolf** [comment]
ok I downloaded and tried... nothing changed... I tried to change the preferences for the Plugin... Disabled chache, changed the Thumbnail size and the kind of picture... nothing happend...

**Comment by aegypius** [comment]
Is the plugin currently activated on your site ? 

Maybe i can found a clue with the html rendering.

(Adding a custom logger to the next features ;) )

**Comment by Honigkuchenwolf** [comment]
is now activated unde rthe title Wen-M in the sidebar:

http://hokuwo.de/

**Comment by aegypius** [comment]
Ok thanks, CSS are correctly injected into the head of the page but the widget is not displayed at all in the sidebar, this is weird !

I've just installed suffusion theme it seems to work.
I saw that you actually use WP-Super-Cache :
Which other plugins do you currently use ?

**Comment by aegypius** [comment]
I've just release a new maintenance version with debug : 
http://cloud.github.com/downloads/aegypius/wp-da-widgets/0.1.3-maint-2.zip

**Comment by Honigkuchenwolf** [comment]
Add Meta Tags version 1.7
Aksimet version 2.2.7
Quote Rotator Version 3.5.6
Si Captcha Anti Spam version 2.2.8
Wordpress Com Stats version 1.6.1
WP-Konami Version 1.3
WP-Memory-Usage Version 1.1.0
WP-PrettyPhoto Version 1.6
WP Security Scan Version 2.7.1.2
WP Super Cache Version 0.9.9

**Comment by Honigkuchenwolf** [comment]
updatet to the new maintenance but nothing changed

**Comment by aegypius** [comment]
Ok i've just found another bug when deviant name in property box has a leading space.

this is http://cloud.github.com/downloads/aegypius/wp-da-widgets/0.1.3-maint-3.zip

I hope we'll find out what is going on ;)

**Comment by Honigkuchenwolf** [comment]
updated... nothing changed _buhuhuhu_

**Comment by aegypius** [comment]
F**\* ! I have to find another idea ;)

**Comment by aegypius** [comment]
Can you checkout your cache directory if there is some da-widgets-\* (might be in wp-content/cache/ directory)

**Comment by Honigkuchenwolf** [comment]
I found the following file: da-widgets.php
It's in the following directory: /wp-content/plugins/aegypius-wp-da-widgets-813e7be

nothing other where found.

**Comment by aegypius** [comment]
ok try to create a new directory : 
/wp-content/cache (this the default cache directory in WordPress) 
You must set the rights permissions to user webserver user (or to 777 if you use a FTP client)

**Comment by Honigkuchenwolf** [comment]
oh it's allready existing...

**Comment by aegypius** [comment]
something in it ?

**Comment by Honigkuchenwolf** [comment]
and is set on 777 (ftp client) but the file isn't there

**Comment by Honigkuchenwolf** [comment]
there are many wp-chache files, a htaccess, and two folders

**Comment by aegypius** [comment]
no da-widgets-\* files in the cache directory at all ?

**Comment by Honigkuchenwolf** [comment]
nope... no da-widget file not in the folder nor in any subfolder

**Comment by aegypius** [comment]
Ok seems to be a cache problem or something like that.
I will add more checks for that.

**Comment by Honigkuchenwolf** [comment]
I've disabled the cache function of your plugin all the time, but even when I activate it your file doesn't appear.

**Comment by aegypius** [comment]
I've just release 0.1.3-m4, with more functional checks.
You can download it here : http://github.com/downloads/aegypius/wp-da-widgets/0.1.3-maint-4.zip (broken)

**Comment by Honigkuchenwolf** [comment]
the link says File not found...

**Comment by aegypius** [comment]
Seems to have a small problem with downloads on github try this one : 
http://cloud.github.com/downloads/aegypius/wp-da-widgets/0.1.3-maint-4.zip

**Comment by Honigkuchenwolf** [comment]
ok... now I've on the controll panel of the Plugin the following message: Some issues can occure when open_basedir is set (/www/htdocs/w00aa2aa/:/tmp:/usr/bin:/www/htdocs/w00aa2aa:/bin:/usr/local/bin:/usr/share/php).

**Comment by aegypius** [comment]
Ok; It seems normal because it was the first message you had with curl.
But if it still don't work there a missing test somewhere.

**Comment by Honigkuchenwolf** [comment]
oh yeah It's still not working, as you can see on my page... or did I missed something? have I redo the widget after an update? (sorry I'm not that fond in programming)

**Comment by aegypius** [comment]
No problem ;)
Have you uninstalled any other version of the plugin ? (keep only the latest)

**Comment by Honigkuchenwolf** [comment]
yeah they are all uninstalled, as I can't update from wordpress I uninstall the old plugin first before I Install the new one.

**Comment by aegypius** [comment]
Here's a new [release](http://cloud.github.com/downloads/aegypius/wp-da-widgets/0.1.3-maint-5.zip). I changed the way I test cache write.
I added too the possibility to clean all the plugin cache.

**Comment by Honigkuchenwolf** [comment]
ok... installed... and deleted the cache but nothing else happend... the Warning in the Plugin panel is the same...

**Comment by aegypius** [comment]
Ok thanks ! I found a pal that currently seems to have the same problem. I will digg this out !

**Comment by Honigkuchenwolf** [comment]
WOHOO!

**Comment by aegypius** [comment]
Last [maintenance release](http://cloud.github.com/downloads/aegypius/wp-da-widgets/0.1.3-maint-6.zip) i hope !

**Comment by Honigkuchenwolf** [comment]
nothing changed... damn it!

**Comment by aegypius** [comment]
argh ! I will push the 0.1.4 version to wordpress because there is a lot of change since the begin of this issue and keep looking for that from this point !

**Comment by Honigkuchenwolf** [comment]
ok I'l update to version 0.1.4

**Comment by aegypius** [comment]
Yet another [maintenance release](http://cloud.github.com/downloads/aegypius/wp-da-widgets/0.1.5-pre1.zip).

This release has _a lot_ of debug. 

Please try it when you have a moment !

Thanks

**Comment by Honigkuchenwolf** [comment]
updated and tried...

but nope nothing new...

**Comment by aegypius** [comment]
Ok i understand your mistake now ! 
In your widget config you only have to put your deviant username not the full feed url, here the content of your settings :

```
[title] => Wen-M
[type] => 2
[deviant] => http://backend.deviantart.com/rss.xml?q=gallery%3AWen-M%2F8496170&type=deviation&offset=0
[items] => 4
[rating] => all
```

You must setup these settings :

```
[title] => Wen-M
[type] => 2
[deviant] => wen-m
[items] => 4
[rating] => all
```

Please give it a try and tell me if it works !

**Comment by Honigkuchenwolf** [comment]
... wow yeah it functions... now I only have to get those points away and two beside each other...

**Comment by aegypius** [comment]
Ok, what a relief ! 

You might have to clean your cache ! For the list points let's try this hack in your theme :
    .da-widgets {list-style: none;}

**Comment by Honigkuchenwolf** [comment]
where should I enter this hack?

**Comment by aegypius** [comment]
in a css file in your theme or you can wait for 0.1.5 ;)

**Comment by Honigkuchenwolf** [comment]
I'l wait :-P

**Comment by aegypius** [comment]
0.1.5 will be released soon ! Thanks again for your patience and your help to make this plugin better ;)

**Comment by Honigkuchenwolf** [comment]
hehe np.
