### ISSUE TITLE
thumb not properly displayed

### ISSUE THREAD

**Issue by Honigkuchenwolf** [aegypius/wp-da-widgets#2]
hey today I've an other issue.

one of the four thumbnails isn't displayed properly.

what could be the reason for that?

After deleting cache the problem is solved... could I go round that problem if I disable the cached modus?

**Comment by aegypius** [comment]
Hi ! 

I've just release [0.1.5](http://github.com/aegypius/wp-da-widgets/zipball/0.1.5) that should rely on a new version of my image processing library that should correct some weird issues (resize error, black canvas on image with a huge aspect ratio, etc...)

This feature has been postpone until i finish the rewriting of this library.

But if your issue occurs frequently, I will check why it happens ;)

**Comment by Honigkuchenwolf** [comment]
hum the dots before the pictures are even now there...

**Comment by aegypius** [comment]
In 0.1.5 you can customize CSS in global options so i neutralized as much as possible the default styles that was used in previous versions.

You might clean your cache too,  not my plugin's cache but WP_Cache's cache.

**Comment by Honigkuchenwolf** [comment]
i deleted cache I disabled every plugin I have nothing changed... _hmpf_

**Comment by aegypius** [comment]
Fixed
