### ISSUE TITLE
feature Idea

### ISSUE THREAD

**Issue by Honigkuchenwolf** [aegypius/wp-da-widgets#3]
hy,

I've got an Idea for future releases.

Could it be possible to get n option if I wanna like show pictures of the scraps section of a deviant gallery too?

(a hook I can set for yes or no. Like I can choose to show adult content or not)

and would it possible to choose to show only special folders of the gallery of an deviantart member?
many artists have splitt their galeries in many folder one for every project they work on...

**Comment by aegypius** [comment]
Hi ! 

This is a great idea to get scraps too.
I will look for that for the next release !

Getting special folders is harder to do because we have to check for the list but I will search how to achieve that.

**Comment by aegypius** [comment]
I've just added scraps support for galleries in the 0.1x branch it will be release in 0.1.6

For custom categories I have a clue but as I said in my previous post it maybe harder to achieve

**Comment by Honigkuchenwolf** [comment]
hehe was only an idea ;)

**Comment by aegypius** [comment]
Ok, so custom categories are working now, I need just to do a little more clean up and performance tuning.

**Comment by aegypius** [comment]
I've just released 0.1.6 ! Please give it a try ;)

**Comment by Honigkuchenwolf** [comment]
Have installed it,

looks nice, and functions... but can only take one category ;) not 2,3 or more (end less than complete) XD

**Comment by aegypius** [comment]
Yes, for the moment only one category can be selected due to feed structure in deviantART backend. I've noticed some performance issues when retrieving categories, I will update admin code to speed up things for 0.1.7.

With a chance, category multi-selection support will be added for 0.1.8 when these performance issues will be fixed.
