### ISSUE TITLE
Thumbnails not displaying

### ISSUE THREAD

**Issue by urdsama777** [aegypius/wp-da-widgets#5]
Hi, I installed the widget, and everything looks good - I'm able to connect to the gallery and call up images, but when I check the "thumbnail generation" box nothing is displayed.

So at the moment I can display either full size images or nothing at all. Any idea how to fix this? I am now on WP 3.3

Thank you in advance! Been looking for something just like this for a long time. Really hope I can get it working. :)

~Olga

**Comment by aegypius** [comment]
Hi, for the moment i non longer use Wordpress for my personal usage.

I will install a fresh WP 3.3 and test it.

Tumbnail generation is based on GD and required allow_url_fopen = On or curl if available.

**Comment by urdsama777** [comment]
thank you so much for looking into this! I know enough code to modify the files, just let me know where to tinker with what. :)

**Comment by aegypius** [comment]
So far nothing seems to break thumbnail generation on my fresh install. I will continue my tests.

**Comment by aegypius** [comment]
I guess you are running wp-da-widgets 0.1.7 .

Could you try, the latest : https://github.com/aegypius/wp-da-widgets/zipball/0.2.0

I made a couple of fixes.

**Comment by urdsama777** [comment]
hello hello! I installed the latest version, and the thumbnails still do not show up. It's weird, because the links to the deviations function, I can click and go to the individual DA pages, I just can't see the thumbs on my blog. 

I made a screencap to show you what it looks like. http://east-27.com/temp/widgets_cap.jpg 

Gosh, I'm so close I can taste it. XD This plugin is _exactly_ what I needed. Please let me know if you know what could be causing the issue?

**Comment by urdsama777** [comment]
P.S.: these are my current settings on the dash: http://east-27.com/temp/widgets_cap2.jpg

**Comment by aegypius** [comment]
Ok thanks for your tests, for the moment i have no Idea what is going 
on on your site.

Could you give me your widget setup too. Maybe it's related for the 
"deviant" you are trying to display.

In addition, i will work on more setup checks to ensure everything is 
fine.

aegypius
Think, Experiment & Share.

**Comment by urdsama777** [comment]
Sure thing, here it is: http://east-27.com/temp/widgets_cap3.jpg  

Could it be some sort of permissions issue? I wish there was a way to give you guest access into the dashboard. :/ Would probably be easier if you could poke around directly

**Comment by aegypius** [comment]
Thanks, I don't really thing that an access could help me. But you could send me the debug log file which is located in wp-content/cache/da-widgets-*.log.

I've just tested with your configuration and it works on my fresh install (http://wordpress.hq.aegypius.com/)

Make sure you have some files in your wp-content/cache directory.

**Comment by urdsama777** [comment]
_HUH_ well lookit that.

There is only file in my wp-content/cache directory, i placed a copy here: http://east-27.com/temp/da-widgets-write-test

Let me also say that my wordpress is installed in a separate directory. The index file is in the public root directory, but it refers to the install that's in the separate directory. Do you think that is what's causing the issue? :\

**Comment by aegypius** [comment]
Hi, 

This may cause an issue, some of my setup tests assumes that wordpress is installed with my standard ways. The fact that you have the write test file in your cache directory shows that the write test is working but i may have an issue on the thumbnail part (which determine where the thumbnails are stored). 

Could you send me the directory listing of your setup or an archive of your setup for a more efficient way to fix this issue.

I'm sorry that this issue take so long to resolve, I hope we can solve it as soon as possible.

Thanks again for your support !

**Comment by urdsama777** [comment]
Of course, here is the copy of my WP setup (minus the uploaded images to cut down on filesize): http://east-27.com/temp/directory_setup.zip   

And no, thank YOU for your incredible patience! :D I am very grateful for all of your help.

**Comment by aegypius** [comment]
@urdsama777 : After 6 months of patience, i've just released an updated version of this plugin [0.2.1](https://github.com/aegypius/wp-da-widgets/zipball/0.2.1) is available here.

If you still want to try if it fixes your issues, please let' me know ;)
